### ISSUE TITLE
Memory leaks detected when running test part in Makefile

### ISSUE THREAD

**Issue by fCorleone** [kgabis/parson#103]
Some memory leaks detected when running test part in Makefile.
Detail information :
```
=================================================================
==29999==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 11992 byte(s) in 28 object(s) allocated from:
    #0 0x7f208faa1602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x401910 in counted_malloc /home/mfc_fuzz/newprogram/parson/tests.c:649

Direct leak of 1097 byte(s) in 1 object(s) allocated from:
    #0 0x7f208faa1602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x40a8a4 in read_file /home/mfc_fuzz/newprogram/parson/tests.c:632
    #2 0x40a8a4 in test_suite_9 /home/mfc_fuzz/newprogram/parson/tests.c:513

Indirect leak of 54438 byte(s) in 2262 object(s) allocated from:
    #0 0x7f208faa1602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x401910 in counted_malloc /home/mfc_fuzz/newprogram/parson/tests.c:649
```

**Comment by kgabis** [comment]
I don't manage memory in tests.c so leaks are expected there (see https://github.com/kgabis/parson/issues/97)
