### ISSUE TITLE
Memory Leak in tests.c

### ISSUE THREAD

**Issue by raminfp** [kgabis/parson#118]
Hi @kgabis 

```bash
CC = gcc
CFLAGS = -fsanitize=address -O0 -g -Wall -Wextra -std=c89 -pedantic-errors

CPPC = g++
CPPFLAGS = -O0 -g -Wall -Wextra

all: test testcpp

.PHONY: test testcpp
test: tests.c parson.c
        $(CC) $(CFLAGS) -o $@ tests.c parson.c
        ./$@

testcpp: tests.c parson.c
        $(CPPC) $(CPPFLAGS) -o $@ tests.c parson.c
        ./$@

clean:
        rm -f test *.o
```
If you add `-fsanitize=address` to CFLAGS, and when you run `make`, we get mem leak of  your tests.c code,

## Output 

```bash
Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d672c816 in json_value_init_array /root/parson/parson.c:1343
    #3 0x55f5d67299fb in parse_array_value /root/parson/parson.c:775
    #4 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #5 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #6 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #7 0x55f5d671e15b in main /root/parson/tests.c:73
    #8 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d6727c8c in json_value_init_string_no_copy /root/parson/parson.c:538
    #3 0x55f5d672a1af in parse_string_value /root/parson/parson.c:824
    #4 0x55f5d6728fe3 in parse_value /root/parson/parson.c:696
    #5 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #6 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #7 0x55f5d6729478 in parse_object_value /root/parson/parson.c:742
    #8 0x55f5d6728fbc in parse_value /root/parson/parson.c:692
    #9 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #10 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #11 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #12 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #13 0x55f5d671e15b in main /root/parson/tests.c:73
    #14 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d672cba4 in json_value_init_null /root/parson/parson.c:1406
    #3 0x55f5d672a589 in parse_null_value /root/parson/parson.c:861
    #4 0x55f5d672900d in parse_value /root/parson/parson.c:704
    #5 0x55f5d6729478 in parse_object_value /root/parson/parson.c:742
    #6 0x55f5d6728fbc in parse_value /root/parson/parson.c:692
    #7 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #8 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #9 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #10 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #11 0x55f5d671e15b in main /root/parson/tests.c:73
    #12 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d672c71b in json_value_init_object /root/parson/parson.c:1328
    #3 0x55f5d672904b in parse_object_value /root/parson/parson.c:714
    #4 0x55f5d6728fbc in parse_value /root/parson/parson.c:692
    #5 0x55f5d6729478 in parse_object_value /root/parson/parson.c:742
    #6 0x55f5d6728fbc in parse_value /root/parson/parson.c:692
    #7 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #8 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #9 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #10 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #11 0x55f5d671e15b in main /root/parson/tests.c:73
    #12 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d672c816 in json_value_init_array /root/parson/parson.c:1343
    #3 0x55f5d67299fb in parse_array_value /root/parson/parson.c:775
    #4 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #5 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #6 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #7 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #8 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #9 0x55f5d671e15b in main /root/parson/tests.c:73
    #10 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d672cac4 in json_value_init_boolean /root/parson/parson.c:1395
    #3 0x55f5d672a251 in parse_boolean_value /root/parson/parson.c:837
    #4 0x55f5d6728ff1 in parse_value /root/parson/parson.c:698
    #5 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #6 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #7 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #8 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #9 0x55f5d671e15b in main /root/parson/tests.c:73
    #10 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fc996f06d28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
    #1 0x55f5d672559f in counted_malloc /root/parson/tests.c:649
    #2 0x55f5d672cac4 in json_value_init_boolean /root/parson/parson.c:1395
    #3 0x55f5d672a2b1 in parse_boolean_value /root/parson/parson.c:840
    #4 0x55f5d6728ff1 in parse_value /root/parson/parson.c:698
    #5 0x55f5d6729c51 in parse_array_value /root/parson/parson.c:791
    #6 0x55f5d6728fd5 in parse_value /root/parson/parson.c:694
    #7 0x55f5d672bb01 in json_parse_string /root/parson/parson.c:1129
    #8 0x55f5d671e239 in test_suite_1 /root/parson/tests.c:94
    #9 0x55f5d671e15b in main /root/parson/tests.c:73
    #10 0x7fc996ac62e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

```

Thanks,
Ramin

**Comment by kgabis** [comment]
See https://github.com/kgabis/parson/issues/103
