### ISSUE TITLE
Memory leak when parsing failed

### ISSUE THREAD

**Issue by grievejia** [kgabis/parson#82]
Here's the input that will trigger the issue:
[leak.txt](https://github.com/kgabis/parson/files/1275313/leak.txt)
Feed it into the json_parse_string() function on master(e410fc7) built with AddressSanitizer will crash the program:
```
> ./parse leak.txt
=================================================================
==9905==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x4d6250 in __interceptor_malloc /home/grieve/LLVM/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:88
    #1 0x521788 in process_string (/home/grieve/scratch/parson/main+0x521788)
    #2 0x51f29e in get_quoted_string (/home/grieve/scratch/parson/main+0x51f29e)
    #3 0x51ba2d in parse_object_value (/home/grieve/scratch/parson/main+0x51ba2d)
    #4 0x50e8d5 in parse_value (/home/grieve/scratch/parson/main+0x50e8d5)
    #5 0x50e137 in json_parse_string (/home/grieve/scratch/parson/main+0x50e137)
    #6 0x50d993 in main (/home/grieve/scratch/parson/main+0x50d993)
    #7 0x7f80f45784c9 in __libc_start_main (/usr/lib/libc.so.6+0x204c9)

SUMMARY: AddressSanitizer: 2 byte(s) leaked in 1 allocation(s).
```
Here's the full source code of parse.c I used in testing:
```c
#include "parson.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
  if (argc > 1) {
    const char* filename = argv[1];
    FILE* file = fopen(filename, "rb");
    if (file != NULL) {
      fseek(file, 0, SEEK_END);
      long file_size = ftell(file);
      rewind(file);

      char* buf = (char*)malloc(file_size + 1);
      if (buf != NULL) {
        fread(buf, file_size, 1, file);
        buf[file_size] = 0;

        JSON_Value* val = json_parse_string(buf);
        if (val != NULL) {
          json_value_free(val);
        }

        free(buf);
      }
      fclose(file);
    }
  }
}
```

**Comment by kgabis** [comment]
Thanks, this should be fixed in https://github.com/kgabis/parson/commit/d485b068c738f268b12f889249532a84244ca27d
